apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: mrmyiagi/grafana:latest
        imagePullPolicy: Always
        env:
        - name: GF_SERVER_ROOT_URL
          valueFrom:
            configMapKeyRef:
              name: grafana-root-url
              key: GF_SERVER_ROOT_URL