apiVersion: apps/v1
kind: Deployment
metadata:
  name: wekan
  labels:
    app: wekan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wekan
  template:
    metadata:
      labels:
        app: wekan
    spec:
      containers:
      - name: wekan
        image: wekanteam/wekan:latest
        ports:
        - containerPort: 8080
          name: wekan
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-db-url
                key: MONGO_URL
          - name: ROOT_URL
            valueFrom:
              configMapKeyRef:
                name: wekan-root-url
                key: ROOT_URL