# prometheus.yml
global:
    scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
  - job_name: wekan
    static_configs:
      - targets: ['wekan:8080']   
  - job_name: node-exporter-prometheus-node-exporter
    static_configs:
      - targets: ['node-exporter-prometheus-node-exporter:9100']        
  - job_name: kube-state-metrics
    static_configs:
      - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']